# terminals: array of names of relay channels, any string will work. 
#            these labels will be used for the control panel page "switches"

# stages: array of functions of relay channels, AS defined in modes.py
#   R = (R) 24VAC power 
#   A = any (wildcard for toggle)
#   1 = stage 1
#   2 = stage 2
#   3 = stage 3
#   G = (G) fan
#   O = (O) reversing (engaged in cooling, manufacturer dependent may vary)
#   B = (Black) reversing (engaged in heating, manufacturer dependent may vary)
# DO NOT CONNECT TO -24VAC (C/Common/usually blue) these should be the only wires you need

# colors: array of hex "0xDEADBEEF" format colors
[DEFAULT]
terminals=[R, W1, W2, G/O/B]
colors=['#E3170D', '#FFF8DC', '#C9C9C9', '#32CD32']

[SingleStageHeater]
terminals=[R, W1, G]
colors=['#E3170D', '#FFF8DC', '#32CD32']

[TwoStageHeater]
terminals=[R, W1, W2, G]
colors=['#E3170D', '#FFF8DC', '#C9C9C9', '#32CD32']

[ThreeStageHeater]
terminals=[R, W1, W2, W3]
colors=['#E3170D', '#FFF8DC', '#C9C9C9', '#838B83']

[SingleStageAC]
terminals=[R, Y1, G]
colors=['#E3170D', '#FFFF4d', '#32CD32']

[TwoStageAC]
terminals=[R, Y1, Y2, G]
colors=['#E3170D', '#FFFF4d', '#CCCC00', '#32CD32']

[ThreeStageAC]
terminals=[R, W1, W2, W3]
colors=['#E3170D', '#FFFF4d', '#CCCC00', '#808000']

[SingleStageHeatPump]
terminals=[R, Y1, O/B, G]
colors=['#E3170D', '#FFFF4d', '#FF8000', '#32CD32']

[TwoStageHeatPump]
terminals=[R, Y1, Y2, O/B]
colors=['#E3170D', '#FFFF4d', '#CCCC00', '#FF8000',]

[Custom]
terminals=[R, W1, W2, G/O/B]
colors=['#E3170D', '#FFF8DC', '#C9C9C9', '#68f9d8']
